name: gnostr-bot

on:
  schedule:
    - cron: '0 * * * *' # “At minute zero.”
  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'

env:
  GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        tag: ["latest"]
    runs-on: ${{ matrix.os }}
    container: rust:${{ matrix.tag }}

    steps:
      - name: checkout@v3 fetch-depth submodules set-safe-dir true
        uses: actions/checkout@v3
        if: ${{ !env.ACT }}
        with:
          fetch-depth: '0'
          submodules: 'true'
          set-safe-directory: 'true'
      - run: git config --global --add safe.directory /__w/gnostr/gnostr || true
      - run: printenv
      - run: apt-get update && apt-get install apt -y
      - run: apt-get install cmake make sudo -y #&& cmake -S .
      - run: apt-get install golang-1.19-go golang-1.19-src golang-go golang-src
      - run: apt-get install -y cargo-doc clang-14-doc wasi-libc cmake-doc cmake-format elpa-cmake-mode ninja-build autopoint gettext-doc libasprintf-dev libgettextpo-dev lrzip llvm-14-doc python3-setuptools python-pygments-doc
      - run: apt-get install -y lib32stdc++6 libc6-i386 lib32gcc-s1 ttf-bitstream-vera lld-14 || true
      - run: apt-get install binfmt-support cargo clang clang-14 cmake cmake-data gettext gettext-base libarchive13 libclang-common-14-dev libclang-cpp14 libclang-rt-14-dev libclang1-14 libcurl3-nss libgc1 libgit2-1.5 libhttp-parser2.9 libjsoncpp25 libllvm14 libmbedcrypto7 libmbedtls14 libmbedx509-1 libnspr4 libnss3 libobjc-12-dev libobjc4 libpfm4 libpipeline1 librhash0 libstd-rust-1.63 libstd-rust-dev libuv1 libz3-4 libz3-dev llvm-14 llvm-14-dev llvm-14-linker-tools llvm-14-runtime llvm-14-tools nss-plugin-pem python-is-python3 python3-pkg-resources python3-pygments python3-yaml rustc sudo -y
      - run: cargo install --force gnostr-sha256
      - run: cargo install --force gnostr-bins
      ## NOTE: make gnostr-am is the non-cmake build
      - run: make gnostr-am && echo $(which gnostr-am)
      - run: make gnostr gnostr-install && echo $(which gnostr)
      - run: gnostr-nip --sec $(gnostr-sha256) | gnostr-post-event
        if: github.event_name == 'pull_request'
      - run: gnostr-nip --sec $(gnostr-sha256 $(gnostr-weeble)) | gnostr-post-event
        if: github.event_name == 'pull_request'
      - run: gnostr-nip --sec $(gnostr-sha256 $(gnostr-weeble)$(gnostr-blockheight)) | gnostr-post-event
        if: github.event_name == 'pull_request'
      - run: gnostr-am --sec $(gnostr-sha256 $(gnostr-weeble)) --content $(gnostr-weeble)/$(gnostr-blockheight)/$(gnostr-wobble) -t gnostr --tag weeble $(gnostr-weeble) --tag blockheight $(gnostr-blockheight) --tag wobble $(gnostr-wobble)
        if: github.event_name == 'pull_request'

      - run: echo $(date +%s)
      - run: ls -a
      - run: $(which gnostr-am) --sec $(gnostr-sha256 $(gnostr-weeble)) -t gnostr --tag weeble $(gnostr-weeble) --tag wobble $(gnostr-wobble) --tag blockheight $(gnostr-blockheight) --content "$(gnostr-weeble)/$(gnostr-blockheight)/$(gnostr-wobble)" | gnostr-post-event wss://relay.damus.io
      - run: $(which gnostr-am) --sec $(gnostr-sha256 $(gnostr-weeble)$(gnostr-blockheight)) -t gnostr --tag weeble $(gnostr-weeble) --tag wobble $(gnostr-wobble) --tag blockheight $(gnostr-blockheight) --content "$(gnostr-weeble)/$(gnostr-blockheight)/$(gnostr-wobble)" | gnostr-post-event wss://relay.damus.io
      - run: gnostr-nip --sec $(gnostr-sha256)                                       | gnostr-post-event
      - run: gnostr-nip --sec $(gnostr-sha256 $(gnostr-weeble))                      | gnostr-post-event
      - run: gnostr-nip --sec $(gnostr-sha256 $(gnostr-weeble)$(gnostr-blockheight)) | gnostr-post-event
      - run: cmake . && make gnostr gnostr-install
