name: gnostr-bot

on:
  schedule:
    - cron: '0 * * * *' # “At minute zero.”
  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'

env:
  GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        tag: ["latest"]
    runs-on: ${{ matrix.os }}
    container: rust:${{ matrix.tag }}

    steps:
      - name: checkout@v3 fetch-depth submodules set-safe-dir true
        uses: actions/checkout@v3
        if: ${{ !env.ACT }}
        with:
          fetch-depth: '0'
          submodules: 'true'
          set-safe-directory: 'true'
      - run: git config --global --add safe.directory /__w/gnostr/gnostr || true
      - run: printenv
      - run: apt-get update && apt-get install binfmt-support cargo clang clang-14 cmake cmake-data gettext gettext-base lib32gcc-s1 lib32stdc++6 libarchive13 libc6-i386 libclang-common-14-dev libclang-cpp14 libclang-rt-14-dev libclang1-14 libcurl3-nss libgc1 libgit2-1.5 libhttp-parser2.9 libjsoncpp25 libllvm14 libmbedcrypto7 libmbedtls14 libmbedx509-1 libnspr4 libnss3 libobjc-12-dev libobjc4 libpfm4 libpipeline1 librhash0 libstd-rust-1.63 libstd-rust-dev libuv1 libz3-4 libz3-dev llvm-14 llvm-14-dev llvm-14-linker-tools llvm-14-runtime llvm-14-tools nss-plugin-pem python-is-python3 python3-pkg-resources python3-pygments python3-yaml rustc sudo -y
      - run: cargo install gnostr-sha256
      - run: cargo install gnostr-bins
      - run: rm -rf CMakeCache.txt
      - run: rm -rf CMakeFiles
      - run: cmake .
      - run: V=1 make detect gnostr gnostr-install
      - run: echo $(gnostr-sha256 $(git diff HEAD))
      - run: DATE=$(date +%s) && gnostr --sec $(gnostr-sha256 $DATE) -t gnostr --tag weeble $(gnostr-weeble) --tag wobble $(gnostr-wobble) --content 'Somebody is developing with gnostr!' | gnostr-post-event wss://nos.lol
      - run: DATE=$(date +%s) && gnostr --sec $(gnostr-sha256 $DATE) -t gnostr --tag weeble $(gnostr-weeble) --tag wobble $(gnostr-wobble) --content "WEEBLE:$(gnostr-weeble):BLOCKHEIGHT:$(gnostr-blockheight):WOBBLE:$(gnostr-wobble)" | gnostr-post-event wss://relay.damus.io
 
