name: gnostr

# Controls when the action will run.
on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'

  workflow_dispatch:

env:
  GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        tag: [3.19]

    #node:lts-alpine3.19
    container: node:lts-alpine${{ matrix.tag }}

    steps:
      ## notice: this is a pre checkout step
      ## notice: additional operations can be done prior to checkout
      - run: apk update && apk add bash cmake curl git make pipx python3 && pipx install virtualenv
      - run: printenv
      - run: git config --global --add safe.directory /__w/gnostr/gnostr
      - run: touch ~/GITHUB_TOKEN.txt
      - name: checkout@v3 fetch-depth submodules set-safe-dir true
        uses: actions/checkout@v3
        with:
          fetch-depth: '10'
          submodules: 'true'
          set-safe-directory: 'true'
      ## notice: these are post checkout steps
      - run: apk update && apk add autoconf automake build-base cargo openssl-dev libtool linux-headers make sudo
      - run: rm CMakeCache.txt || echo && cmake .
      - run: make
      - run: make clean
      - run: make help
      - run: make libsecp256k1.a || rm -rf deps/secp256k1 && make libsecp256k1.a
      - run: rm gnostr || true
      - run: make gnostr bins && cp gnostr gnostr-alpine
      - run: make gnostr-install
      - run: gnostr
      ## TODO: add ssh config to act sequence
      - run: rm -rf .venv
