name: gnostr

# Controls when the action will run.
on:
  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    env:
      GNOSTR: "gnostr"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: echo test
        #if: ${{ !env.ACT }}
        run: |
          echo GNOSTR=${{ env.GNOSTR }}
          echo GNOSTR1=${{ env.GNOSTR1 }}
        env:
          GNOSTR1: "GNOSTR1"
      - uses: styfle/cancel-workflow-action@0.11.0
        if: ${{ !env.ACT }}
        with:
          access_token: ${{ github.token }}
      - name: Restore deps
        id: cache-deps-restore
        uses: actions/cache/restore@v3
        if: ${{ !env.ACT }}
        with:
          path: |
            ~/.rustup
          key: ${{ runner.os }}-deps

      - uses: actions/checkout@v3
        with:
          submodules: 'true'
          set-safe-directory: 'true'
          fetch-depth: '10'

      - uses: actions-rs/toolchain@v1.0.6
        #if: ${{ !env.ACT }}
        with:
          toolchain: stable
          default: true
          override: true

      - name: echo GNOSTR
        #if: ${{ !env.ACT }}
        run: |
          echo $GNOSTR

      - name:  apt-get update && apt-get install jq protobuf-compiler || brew install jq protobuf || true
        run: |
          sudo apt-get update && apt-get install automake jq protobuf-compiler || brew install automake jq protobuf || true
          touch ~/GITHUB_TOKEN.txt

      - run: for t in */Cargo.toml;do echo $t;cargo b -r -vv --manifest-path $t ;done
      - run: python3 -m pip install virtualenv

      #- run: rm -rf /home/runner/.rustup || true
      - run: sudo make detect
      - run: mkdir -p ~/bin
      - run: make gnostr-am
      - run: rustup default stable
      #- run: make submodules
      - run: cmake .
      - run: V=1 make gnostr bins
      - run: V=1 make gnostr-install
      - run: V=1 make gnostr-verify-keypair
      #- run: make gnostr
      #- run: V=1 make install
      #- run: V=1 make all
      #- run: V=1 make install || true
      - run: V=1 make gnostr-install || true
      - run: gnostr-nip --sec $(gnostr-sha256) | gnostr-post-event
      - run: V=1 gnostr --sec $(gnostr-sha256 $(gnostr-weeble)) --content '#gnostr!' -t gnostr --tag weeble $(gnostr-weeble) --tag wobble $(gnostr-wobble) --tag blockheight $(gnostr-blockheight) | gnostr-post-event wss://nos.lol
      - run: gnostr --sec $(gnostr-sha256 $(gnostr-weeble)) --content $(gnostr-weeble)/$(gnostr-blockheight)/$(gnostr-wobble) -t gnostr --tag weeble $(gnostr-weeble) --tag blockheight $(gnostr-blockheight) --tag wobble $(gnostr-wobble) | gnostr-post-event wss://relay.damus.io

      #- name: V=1 make gnostr-all
      #  run: V=1 make gnostr-all

      #- name: V=1 make gnostr-install
      #  if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      #  run: V=1 make gnostr-install

      #- name: ./build.cmake.sh
      #  if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      #  run: ./build.cmake.sh

      - name: Save deps
        id: cache-deps-save
        uses: actions/cache/save@v3
        if: ${{ !env.ACT }}
        with:
          path: |
            ~/.rustup
          key: ${{ steps.cache-deps-restore.outputs.cache-primary-key }}

